[book]
authors = ["CypherpunkSamurai"]
language = "en"
multilingual = false
src = "contents"
title = "mdBook GithubActions"
description = "mdBook GithubActions - Automatically publish markdown pages to static github pages"
