name: mdBook Deploy to Target Repo

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      - name: Copy Source
        uses: actions/checkout@v2

      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
          #mdbook-version: '0.4.6'

      - run: cargo install mdbook-latex

      - run: mdbook build

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: ${{ github.actor }}/gitnotes
          publish_dir: ./book
          publish_branch: master
